arb-dir: lib/src/core/localizations/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
untranslated-messages-file: no-translation.log
output-dir: lib/src/core/localizations/generated
synthetic-package: false
